bakecake/bakecake/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('shop.urls'))
]

bakecake/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('catalog/<slug:slug>', views.show_catalog, name='show_catalog')
]

bakecake/shop/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


# Тут описываем свою модель пользователя
class AppUser(AbstractUser):
    pass


class BakeCakeLevels(models.Model):
    level = models.SmallIntegerField('Уровень')
    name = models.CharField('Наименование уровня', max_length=30)
    price = models.FloatField('Цена')
    choice_id = models.SmallIntegerField('Номер', unique=True)

    class Meta:
        verbose_name = 'Уровни тортика'
        verbose_name_plural = 'Уровни тортиков'

    def __str__(self):
        return f'{self.choice_id}. {self.name} : {str(self.price)} Руб.'


class BakeCakeShape(models.Model):
    shape_name = models.CharField('Наименование формы', max_length=50)
    price = models.FloatField('Цена')
    choice_id = models.SmallIntegerField('Номер', unique=True)

    class Meta:
        verbose_name = 'Форма тортика'
        verbose_name_plural = 'Формы тортиков'

    def __str__(self):
        return f'{self.choice_id}. {self.shape_name} : {str(self.price)} Руб.'


class BakeCakeTopping(models.Model):
    topping_name = models.CharField('Название топпинга', max_length=100)
    price = models.FloatField('Цена')
    choice_id = models.SmallIntegerField('Номер', unique=True)

    class Meta:
        verbose_name = 'Топпинг'
        verbose_name_plural = 'Топпинги'

    def __str__(self):
        return f'{self.choice_id}. {self.topping_name} : {str(self.price)} Руб.'


class BakeCakeBerries(models.Model):
    berry_name = models.CharField('ягода', max_length=50)
    price = models.FloatField('Цена')
    choice_id = models.SmallIntegerField('Номер', unique=True)

    class Meta:
        verbose_name = 'Ягода'
        verbose_name_plural = 'Ягоды'

    def __str__(self):
        return f'{self.choice_id}. {self.berry_name} : {str(self.price)} Руб.'


class BakeCakeDecor(models.Model):
    decor_name = models.CharField('Декор', max_length=50)
    price = models.FloatField('Цена')
    choice_id = models.SmallIntegerField('Номер', unique=True)

    class Meta:
        verbose_name = 'Декор'
        verbose_name_plural = 'Декоры'

    def __str__(self):
        return f'{self.choice_id}. {self.decor_name} : {str(self.price)} Руб.'


# Модель тортика
class BakeCake(models.Model):

    levels = models.ForeignKey('BakeCakeLevels', verbose_name='Количество уровней', on_delete=models.CASCADE)
    shape = models.ForeignKey('BakeCakeShape', verbose_name='Форма', on_delete=models.CASCADE)
    topping = models.ForeignKey('BakeCakeTopping', verbose_name='Топинг', on_delete=models.CASCADE)
    berries = models.ForeignKey('BakeCakeBerries', verbose_name='Ягоды', on_delete=models.CASCADE, blank=True, null=True)
    decor = models.ForeignKey('BakeCakeDecor', verbose_name='Декор', on_delete=models.CASCADE, blank=True, null=True)
    inscription = models.CharField('Надпись', max_length=100, blank=True, null=True)
    name = models.CharField('Название', max_length=100, blank=True)
    image = models.ImageField('Изображение', upload_to='media/BakeCakeImages/', blank=True, null=True, default='media/BakeCakeImages/no_image.png')
    catalog = models.ForeignKey('Catalog', verbose_name='В каталоге', on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = 'Торт'
        verbose_name_plural = 'Тортики'

    def __str__(self):
        if self.name:
            return self.name
        else:
            return str(self.pk)

    def get_absolute_url(self):
        return reverse('bakecake-detail', kwargs={'pk': self.pk})


# Модель заказа тортика
class Order(models.Model):
    ...


# Модель каталога тортиков
class Catalog(models.Model):
    name = models.CharField('Название', max_length=50, default='На чаепитие')
    image = models.ImageField('Изображение', upload_to='media/catalog/', default='media/BakeCakeImages/no_image.png')
    slug = models.SlugField('Slug', max_length=100, unique=True, default=uuid.uuid4)

    class Meta:
        verbose_name = 'Каталог'
        verbose_name_plural = 'Каталоги'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Catalog, self).save(*args, **kwargs)

bakecake/shop/views.py
from django.shortcuts import render


# Вью главной страницы
def index(request):

    if request.method == 'GET':

        if 'REG' in request.GET:
            print('Регистрация')
            print(f'Телефон = {request.GET.get("REG")}')

        elif 'LEVELS' in request.GET:
            print('Создана заявка')
            print(f'Levels = {request.GET.get("LEVELS")}')
            print(f'Form = {request.GET.get("FORM")}')
            print(f'Topping = {request.GET.get("TOPPING")}')
            print(f'Berries = {request.GET.get("BERRIES")}')
            print(f'Decor = {request.GET.get("DECOR")}')
            print(f'Words = {request.GET.get("WORDS")}')
            print(f'Comments = {request.GET.get("COMMENTS")}')
            print(f'Name = {request.GET.get("NAME")}')
            print(f'Phone = {request.GET.get("PHONE")}')
            print(f'Email = {request.GET.get("EMAIL")}')
            print(f'Address = {request.GET.get("ADDRESS")}')
            print(f'Date = {request.GET.get("DATE")}')
            print(f'Time = {request.GET.get("TIME")}')
            print(f'Deliv comment = {request.GET.get("DELIVCOMMENTS")}')

        context = {

        }

        return render(request, 'shop/index.html', context)

    else:

        context = {

        }

        return render(request, 'shop/index.html', context)


# Вью каталога тортиков
def show_catalog(request):

    context = {

    }

    return render(request, 'shop/show_catalog.html', context)


# Вью корзины
def show_cart(request):

    context = {

    }

    return render(request, 'shop/show_cart.html', context)


# Вью личного кабинета сладкоежки
def show_cabinet(request):

    context = {

    }

    return render(request, 'shop/show_cabinet.html', context)

bakecake/shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/Style.css' %}">
	<!-- Для разработки: -->
	<script src="https://unpkg.com/vue@3"></script>
	<!-- Для продакшина: -->
	<!-- <script src="https://unpkg.com/vue@3/dist/vue.global.prod.js"></script> -->
	<script src="https://unpkg.com/vee-validate"></script>
	<title>Тортики</title>
</head>
<body>
<header class="navbar navbar-expand-xl navbar-light fixed-top bg-white py-4">
	<nav class="container">
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<a class="navbar-brand" href="{% url 'shop:index' %}">
			<img src="{% static 'img/Logo.svg' %}" alt="CakeBake">
		</a>
		<div class="collapse navbar-collapse justify-content-end" id="navbar">
			<ul class="navbar-nav">
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="#step3">Создать торт</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="#step2">Каталог</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="#step4">Оплата и доставка</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="#Contacts">Контакты</a>
				</li>
				<li class="nav-item d-block d-xl-flex flex-column align-items-end me-5">
					<small class="fw-lighter text-decoration-none fs_12 cake_blue">8 (495) 000-00-00</small>
					<small class="fw-lighter text-decoration-none fs_12 cake_blue">Пн - Вс 10:00—20:00</small>
				</li>
				<li class="nav-item d-flex align-items-center">
					<a class="nav-link fw-lighter me-1 cake_blue position-relative" href="#">
						<img src="{% static 'img/shopping-cart.svg' %}" alt="">
						<!--метка на иконке, убрать класс d-none чтоб появилась-->
						<span class="position-absolute translate-middle badge rounded-pill cake__bg_pink fs_8 d-none">1</span>
					</a>
					<a class="nav-link fw-lighter me-1 cake_blue position-relative" href="#RegModal" data-bs-toggle="modal">
						<img src="{% static 'img/user.svg' %}" alt="">
						<!--метка на иконке, убрать класс d-none чтоб появилась-->
						<span class="position-absolute translate-middle badge rounded-pill cake__bg_pink fs_8 d-none">1</span>
					</a>
					<a class="nav-link fw-lighter cake_grey fs_12 d-none" href="#">
						Ирина
					</a>
				</li>
			</ul>
		</div>
	</nav>

</header>

{% block content %}

{% endblock content %}

<footer class="mt-5 cake__bg_blue" id="Contacts">
	<div class="container my-5 py-5">
		<div class="row">
			<div class="col-4 col-xl-2 d-flex flex-column">
				<div>
					<img src="{% static 'img/Logo.svg' %}" alt="CakeBake" class="mb-2">
				</div>
				<small class="text-white fs_12">©2022 CakeBake</small>
				<small class="text-white fs_12">Все права защищены.</small>
				<div class="flex-grow-1 d-flex align-items-end">
					<small class="text-white fs_12">г. Москва,  Большой Козловский пер., д. 12</small>
				</div>
			</div>
			<div class="col-4 col-xl-2 d-flex flex-column">
				<a href="#" class="text-decoration-none text-white">На свадьбу</a>
				<a href="#" class="text-decoration-none text-white">На день рождения</a>
				<a href="#" class="text-decoration-none text-white">На чаепитие</a>
			</div>
			<div class="col-4 col-xl-2 d-flex flex-column">
				<a href="#step3" class="text-decoration-none text-white">Создать торт</a>
				<a href="#step2" class="text-decoration-none text-white">Каталог</a>
				<a href="#Contacts" class="text-decoration-none text-white">Контакты</a>
			</div>
			<div class="col-12 col-xl-6 d-flex flex-column align-items-start align-items-xl-end mt-3 mt-xl-0">
				<a href="https://vk.com/devmanorg"><img src="{% static 'img/vk.svg' %}" alt="VK" class="mb-3 mb-xl-5"></a>
				<small class="text-white fs_12">8 (495) 000-00-00</small>
				<small class="text-white fs_12">info@cakebake.ru</small>
				<small class="text-white fs_12">Пн - Вс 10:00—20:00</small>
			</div>
		</div>
	</div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<script src="{% static 'js/index.js' %}"></script>
<script src="{% static 'js/registration.js' %}"></script>
</body>
</html>